-----------------------------------------------------------
--  @file:   tts_plan_ctx.ads
--  @input:  plan_ctx.tts
--  @brief:  Plan for measuring context switch overhead between
--           different slot combinations
--  @note:   Code generated by 'ada-sched-tool' tool
-----------------------------------------------------------

with Ada.Real_Time; use Ada.Real_Time;
with System;
with XAda.Dispatching.TTS;
with TT_Mixed_Criticality; use TT_Mixed_Criticality;
with TT_Utilities;

generic
   TT_Priority : System.Priority := System.Priority'Last;
package TTS_Plan_Ctx is
   subtype Criticality_Levels is No_Criticality_Levels;

   Number_Of_Works : constant Positive := 7;

   package TTS is new XAda.Dispatching.TTS
     (Criticality_Levels, Number_Of_Works, TT_Priority);
   package TTU is new TT_Utilities (TTS);
   use TTU;

   ms : constant Time_Span := Milliseconds (1);
   us : constant Time_Span := Microseconds (1);
   zero : constant Time_Span := Time_Span_Zero;

   --  The TT plan
   Plan_Ctx : aliased TTS.Time_Triggered_Plan :=
     (-- 0-10
      --  Plan start
      TT_Slot (Initial,              10 * ms, 7,
               Work_Durations => (Normal => 10 * ms)),
      -- 10-20
      --  Work 1 A. Check Em->In, Em->Re
      TT_Slot (Empty,                10 * ms   ),
      -- 20-30
      --  Em->In
      TT_Slot (Initial,              10 * ms, 1,
               Work_Durations => (Normal => 10 * ms)),
      -- 30-40
      TT_Slot (Empty,                10 * ms   ),
      -- 40-50
      --  Em->Re
      TT_Slot (Final,                10 * ms, 1,
               Work_Durations => (Normal => 10 * ms)),
      -- 50-60
      --  Work 2 A. Check Em->IS, Em->Sy
      TT_Slot (Empty,                10 * ms   ),
      -- 60-70
      --  Em->IS
      TT_Slot (Initial_Sync,         10 * ms, 2),
      -- 70-80
      TT_Slot (Empty,                10 * ms   ),
      -- 80-90
      --  Em->Sy
      TT_Slot (Sync,                 10 * ms, 2,
               Work_Durations => (Normal => 10 * ms)),
      -- 90-100
      --  Work 3 A. Check Em->IC
      TT_Slot (Empty,                10 * ms   ),
      -- 100-110
      --  Em->IC
      TT_Slot (Initial_Continuation, 10 * ms, 3,
               Work_Durations => (Normal => 10 * ms)),
      -- 110-120
      TT_Slot (Empty,                10 * ms   ),
      -- 120-130
      TT_Slot (Final,                10 * ms, 3,
               Work_Durations => (Normal => 10 * ms)),
      -- 130-140
      --  Work 4 A. Check Em->Co
      TT_Slot (Empty,                10 * ms   ),
      -- 140-150
      TT_Slot (Initial,              10 * ms, 4,
               Work_Durations => (Normal => 10 * ms)),
      -- 150-160
      TT_Slot (Empty,                10 * ms   ),
      -- 160-170
      --  Em->Co
      TT_Slot (Continuation,         10 * ms, 4,
               Work_Durations => (Normal => 10 * ms)),
      -- 170-180
      TT_Slot (Empty,                10 * ms   ),
      -- 180-190
      TT_Slot (Final,                10 * ms, 4,
               Work_Durations => (Normal => 10 * ms)),
      -- 190-200
      --  Work 1 B. Check Ho->In, Ho->Re
      TT_Slot (Empty,                10 * ms   ),
      -- 200-210
      TT_Slot (Initial_Continuation, 10 * ms, 5,
               Work_Durations => (Normal => 10 * ms)),
      -- 210-220
      --  Ho->In
      TT_Slot (Initial,              10 * ms, 1,
               Work_Durations => (Normal => 10 * ms)),
      -- 220-230
      TT_Slot (Final,                10 * ms, 5,
               Work_Durations => (Normal => 10 * ms)),
      -- 230-240
      TT_Slot (Empty,                10 * ms   ),
      -- 240-250
      TT_Slot (Initial_Continuation, 10 * ms, 5,
               Work_Durations => (Normal => 10 * ms)),
      -- 250-260
      --  Ho->Re
      TT_Slot (Final,                10 * ms, 1,
               Work_Durations => (Normal => 10 * ms)),
      -- 260-270
      TT_Slot (Final,                10 * ms, 5,
               Work_Durations => (Normal => 10 * ms)),
      -- 270-280
      --  Work 2 B. Check Ho->IS, Ho->Sy
      TT_Slot (Empty,                10 * ms   ),
      -- 280-290
      TT_Slot (Initial_Continuation, 10 * ms, 5,
               Work_Durations => (Normal => 10 * ms)),
      -- 290-300
      --  Ho->IS
      TT_Slot (Initial_Sync,         10 * ms, 2),
      -- 300-310
      TT_Slot (Final,                10 * ms, 5,
               Work_Durations => (Normal => 10 * ms)),
      -- 310-320
      TT_Slot (Empty,                10 * ms   ),
      -- 320-330
      TT_Slot (Initial_Continuation, 10 * ms, 5,
               Work_Durations => (Normal => 10 * ms)),
      -- 330-340
      --  Ho->Sy
      TT_Slot (Sync,                 10 * ms, 2,
               Work_Durations => (Normal => 10 * ms)),
      -- 340-350
      TT_Slot (Final,                10 * ms, 5,
               Work_Durations => (Normal => 10 * ms)),
      -- 350-360
      --  Work 3 B. Check Ho->IC
      TT_Slot (Empty,                10 * ms   ),
      -- 360-370
      TT_Slot (Initial_Continuation, 10 * ms, 5,
               Work_Durations => (Normal => 10 * ms)),
      -- 370-380
      --  Ho->IC
      TT_Slot (Initial_Continuation, 10 * ms, 3,
               Work_Durations => (Normal => 10 * ms)),
      -- 380-390
      TT_Slot (Final,                10 * ms, 5,
               Work_Durations => (Normal => 10 * ms)),
      -- 390-400
      TT_Slot (Empty,                10 * ms   ),
      -- 400-410
      TT_Slot (Final,                10 * ms, 3,
               Work_Durations => (Normal => 10 * ms)),
      -- 410-420
      --  Work 4 B. Check Ho->Co
      TT_Slot (Empty,                10 * ms   ),
      -- 420-430
      TT_Slot (Initial,              10 * ms, 4,
               Work_Durations => (Normal => 10 * ms)),
      -- 430-440
      TT_Slot (Empty,                10 * ms   ),
      -- 440-450
      TT_Slot (Initial_Continuation, 10 * ms, 5,
               Work_Durations => (Normal => 10 * ms)),
      -- 450-460
      --  Ho->Co
      TT_Slot (Continuation,         10 * ms, 4,
               Work_Durations => (Normal => 10 * ms)),
      -- 460-470
      TT_Slot (Final,                10 * ms, 5,
               Work_Durations => (Normal => 10 * ms)),
      -- 470-480
      TT_Slot (Empty,                10 * ms   ),
      -- 480-490
      TT_Slot (Final,                10 * ms, 4,
               Work_Durations => (Normal => 10 * ms)),
      -- 490-500
      --  Work 6. Report task
      TT_Slot (Empty,                10 * ms   ),
      -- 500-510
      TT_Slot (Initial,              10 * ms, 6,
               Work_Durations => (Normal => 10 * ms))
      );

end TTS_Plan_Ctx;
