-----------------------------------------------------------
--  @file:   tts_plan_mf.ads
--  @input:  plan_mf.tts
--  @brief:  Plan for testing multi-frame support using TT patterns
--  @note:   Code generated by 'ada-sched-tool' tool
-----------------------------------------------------------

with Ada.Real_Time; use Ada.Real_Time;
with System;
with XAda.Dispatching.TTS;
with TT_Mixed_Criticality; use TT_Mixed_Criticality;
with TT_Utilities;

generic
   TT_Priority : System.Priority := System.Priority'Last;
package TTS_Plan_MF is
   subtype Criticality_Levels is No_Criticality_Levels;

   Number_Of_Works : constant Positive := 7;

   package TTS is new XAda.Dispatching.TTS
     (Criticality_Levels, Number_Of_Works, TT_Priority);
   package TTU is new TT_Utilities (TTS);
   use TTU;

   ms : constant Time_Span := Milliseconds (1);
   us : constant Time_Span := Microseconds (1);
   zero : constant Time_Span := Time_Span_Zero;

   --  The TT plan
   Plan_MF : aliased TTS.Time_Triggered_Plan :=
     (-- 0-100
      --  00
      TT_Slot (Empty,        100 * ms   ),
      -- 100-300
      --  01 Single slot for 1st seq. start
      TT_Slot (Initial,      200 * ms, 1,
               Work_Durations => (Normal => 50 * ms)),
      -- 300-350
      --  02 Single slot for 2nd seq. start
      TT_Slot (Initial,       50 * ms, 3,
               Work_Durations => (Normal => 50 * ms)),
      -- 350-500
      --  03 Sp. 7, Sync point for sporadic task
      TT_Slot (Initial_Sync, 150 * ms, 7),
      -- 500-550
      --  04 IMF. 2, IMs part
      TT_Slot (Initial,       50 * ms, 2,
               Work_Durations => (Normal => 50 * ms)),
      -- 550-900
      --  05 IMF. 4, IMs part
      TT_Slot (Initial,      350 * ms, 4,
               Work_Durations => (Normal => 50 * ms)),
      -- 900-1100
      --  06 IMF. 2, continuation of Ms part
      TT_Slot (Continuation, 200 * ms, 2,
               Work_Durations => (Normal => 50 * ms)),
      -- 1100-1300
      --  07 IMF. 4, terminal of Ms part
      TT_Slot (Regular,      200 * ms, 4,
               Work_Durations => (Normal => 100 * ms)),
      -- 1300-1350
      --  08 IMF. 2, terminal of Ms part
      TT_Slot (Regular,       50 * ms, 2,
               Work_Durations => (Normal => 50 * ms)),
      -- 1350-1500
      --  09 ET. 6, Sync Point for ET Task
      TT_Slot (Initial_Sync, 150 * ms, 6),
      -- 1500-1650
      --  10 IMF. 4, F part
      TT_Slot (Final,        150 * ms, 4,
               Work_Durations => (Normal => 50 * ms)),
      -- 1650-1780
      --  11 IMF. 2, F part
      TT_Slot (Final,        130 * ms, 2,
               Work_Durations => (Normal => 50 * ms)),
      -- 1780-1900
      --  12 IF. 5, I part of end of plan
      TT_Slot (Initial,      120 * ms, 5,
               Work_Durations => (Normal => 50 * ms)),
      -- 1900-1970
      --  13 ET. 6, F part of synced ET
      TT_Slot (Final,         70 * ms, 6,
               Work_Durations => (Normal => 70 * ms)),
      -- 1970-2020
      --  14 IF. 5, F part of end of plan
      TT_Slot (Final,         50 * ms, 5,
               Work_Durations => (Normal => 50 * ms)),
      -- 2020-2100
      --  15
      TT_Slot (Mode_Change,   80 * ms   )
      );

end TTS_Plan_MF;
