-----------------------------------------------------------
--  @file:   tts_plan_d.ads
--  @input:  plan_d.tts
--  @note:   Code generated by 'ada-sched-tool' tool
-----------------------------------------------------------

with Ada.Real_Time; use Ada.Real_Time;
with System;
with XAda.Dispatching.TTS;
with TT_Mixed_Criticality; use TT_Mixed_Criticality;
with TT_Utilities;

generic
   TT_Priority : System.Priority := System.Priority'Last;
package TTS_Plan_D is
   subtype Criticality_Levels is Dual_Criticality_Levels;

   Number_Of_Works : constant Positive := 5;

   package TTS is new XAda.Dispatching.TTS
     (Criticality_Levels, Number_Of_Works, TT_Priority);
   package TTU is new TT_Utilities (TTS);
   use TTU;

   ms : constant Time_Span := Milliseconds (1);
   us : constant Time_Span := Microseconds (1);
   zero : constant Time_Span := Time_Span_Zero;

   --  The TT plan
   Plan_D : aliased TTS.Time_Triggered_Plan :=
     (-- 0-50
      --  01 Seq. 1, IMs part
      TT_Slot (Initial,       50 * ms, 1,
               Criticality => HI, Work_Durations => (LO => 50 * ms, HI => 50 * ms)),
      -- 50-400
      --  02 Seq. 2, IMs part
      TT_Slot (Initial,      350 * ms, 2,
               Criticality => LO, Work_Durations => (LO => 30 * ms, HI => zero)),
      -- 400-550
      --  03 Single slot for Worker 3
      TT_Slot (Initial,      150 * ms, 3,
               Criticality => HI, Work_Durations => (LO => 30 * ms, HI => 50 * ms)),
      -- 550-750
      --  03 Seq. 1, continuation of Ms part
      TT_Slot (Continuation, 200 * ms, 1,
               Work_Durations => (LO => 30 * ms, HI => 50 * ms)),
      -- 750-900
      --  04 Initial Sync Point for Seq. 5
      TT_Slot (Initial_Sync, 150 * ms, 5,
               Criticality => LO),
      -- 900-1050
      --  05 Seq. 1, terminal of Ms part
      TT_Slot (Regular,      150 * ms, 1,
               Work_Durations => (LO => 30 * ms, HI => 50 * ms)),
      -- 1050-1150
      --  06 Seq. 2, terminal of Ms part
      TT_Slot (Regular,      100 * ms, 2,
               Work_Durations => (LO => 30 * ms, HI => zero)),
      -- 1150-1300
      --  07 Seq. 1, F part
      TT_Slot (Final,        150 * ms, 1,
               Work_Durations => (LO => 30 * ms, HI => 50 * ms)),
      -- 1300-1450
      --  08 Seq. 2, F part
      TT_Slot (Final,        150 * ms, 2,
               Work_Durations => (LO => 30 * ms, HI => zero)),
      -- 1450-1500
      --  09 Single slot for Worker 4
      TT_Slot (Initial,       50 * ms, 4,
               Criticality => LO, Work_Durations => (LO => 40 * ms, HI => zero)),
      -- 1500-1570
      --  10 F part of Seq. 5
      TT_Slot (Final,         70 * ms, 5,
               Work_Durations => (LO => 30 * ms, HI => zero)),
      -- 1570-1650
      --  11 Mode change slot
      TT_Slot (Mode_Change,   80 * ms   )
      );

end TTS_Plan_D;
